repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      files: ^(setup.py|cosmos_rl/|tests/|tools/)
    # Run the formatter.
    - id: ruff-format
      files: ^(setup.py|cosmos_rl/|tests/|tools/)
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
    - id: clang-format
      args: [ -i, --style=Google]
      files: ^cosmos_rl/csrc/
      additional_dependencies: ['clang-format']

