redis = "12800"

[train]
resume = false
epoch = 80
output_dir = "./outputs/llava1-5-7b-p-fsdp4-r-tp2-grpo"
epsilon = 1e-6
optm_name = "AdamW"
optm_lr = 2e-6
optm_impl = "fused"
optm_weight_decay = 0.01
optm_betas = [ 0.9, 0.95,]
optm_warmup_steps = 20
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
param_dtype = "float16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 128
sync_weight_interval = 1

[rollout]
gpu_memory_utilization = 0.7
enable_chunked_prefill = false
max_response_length = 4096
n_generation = 8
batch_size = 4
quantization = "none"

[policy]
model_name_or_path = "llava-hf/llava-1.5-13b-hf"
model_max_length = 4096
model_gradient_checkpointing = true

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_reason1"
experiment_name = "cosmos-reason1-rl"

[train.train_policy]
type = "grpo"
dataset.name = "hiyouga/geometry3k"
dataset.subset = ""
dataset.split = "train"
enable_dataset_cache = false
dataloader_num_workers = 4
dataloader_prefetch_factor = 4
system_prompt = "You are a mathematics expert. For each math problem presented together with an image, thoroughly interpret the visual and textual information and provide a detailed, step-by-step solution, ensuring that your reasoning is clear and precise at every stage."
prompt_column_name = "problem"
response_column_name = "answer"
image_column_name = "images"
video_column_name = ""
reward_function = { boxed_math = 0.9, format = 0.1 }
temperature = 0.9
epsilon_low = 0.2
epsilon_high = 0.2
kl_beta = 0.0
mu_iterations = 1
min_filter_prefix_tokens = 1
mini_batch = 4

[train.ckpt]
enable_checkpoint = true
save_freq = 100
save_mode = "async"

[rollout.parallelism]
n_init_replicas = 1
tp_size = 2
pp_size = 1

[policy.parallelism]
n_init_replicas = 1
tp_size = 1
cp_size = 1
dp_shard_size = 4
pp_size = 1
dp_replicate_size = 1
cp_rotate_method = "allgather"