redis = "12800"
mode = "colocated"

[train]
resume = false
epoch = 1
output_dir = "./outputs/cosmos-policy-libero10-eval"
epsilon = 1e-5
optm_name = "AdamW"
optm_lr = 0.0
optm_impl = "fused"
optm_weight_decay = 0.0
optm_betas = [0.9, 0.95]
optm_warmup_steps = 0
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
master_dtype = "float32"
transfer_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 8
sync_weight_interval = 1
non_text = true

[policy]
model_name_or_path = "nvidia/Cosmos-Policy-LIBERO-Predict2-2B"
model_max_length = 4096
model_gradient_checkpointing = false

[logging]
logger = ['console']
project_name = "cosmos-rl-cosmos-policy"
experiment_name = "cosmos-policy-libero10-eval"

[train.train_policy]
type = "grpo"
trainer_type = "cosmos_policy"
variant = "dapo"
dataset.name = "libero"
dataset.subset = "libero_10"
dataset.split = "train"
dataset.test_size = 496
enable_dataset_cache = false
dataloader_num_workers = 0
dataloader_prefetch_factor = 2
conversation_column_name = "messages"
max_retry_for_on_policy = -1
temperature = 1.0
epsilon_low = 0.2
epsilon_high = 0.28
clip_ratio_c = 3.0
lower_bound_ratio = 10.0
kl_beta = 0.0
mu_iterations = 1
mini_batch = 8
min_filter_prefix_tokens = 1
allowed_outdated_steps = 4

[train.ckpt]
enable_checkpoint = false

[rollout]
backend = "vla"
gpu_memory_utilization = 0.7
enable_chunked_prefill = false
n_generation = 1
batch_size = 4
quantization = "none"
max_response_length = 1024
enforce_eager = false

[policy.parallelism]
n_init_replicas = 8
tp_size = 1
cp_size = 1
dp_shard_size = 1
pp_size = 1
dp_replicate_size = 1
cp_rotate_method = "allgather"

[rollout.parallelism]
n_init_replicas = 8
tp_size = 1
cp_size = 1
dp_shard_size = 1
pp_size = 1
dp_replicate_size = 1

[rollout.sampling_config]
temperature = 1.0
top_p = 1.0
top_k = 50

[validation]
enable = true
freq = 1
val_before_train = true
batch_size = 500
dataset.name = "libero"
dataset.subset = "libero_10"
dataset.split = "val"

[vla]
vla_type = "cosmos-policy"
use_proprio = true
num_envs = 1
proprio_dim = 9
num_images_in_input = 2
training_chunk_size = 16

# WFM-policy-specific settings (passed via config.custom)
[custom]
task_suite_name = "libero_10"
max_steps = 520
num_envs = 1
save_video = true
ckpt_path = "nvidia/Cosmos-Policy-LIBERO-Predict2-2B"
dataset_stats_path = "nvidia/Cosmos-Policy-LIBERO-Predict2-2B/libero_dataset_statistics.json"
t5_text_embeddings_path = "nvidia/Cosmos-Policy-LIBERO-Predict2-2B/libero_t5_embeddings.pkl"
num_denoising_steps = 5
chunk_size = 16
seed = 1
use_jpeg_compression = true
trained_with_image_aug = true
use_variance_scale = false
vae_fp32 = false
