name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-image:
    uses: ./.github/workflows/build_image.yml
    with:
      runs-on: self-hosted
      tag: test${{ github.sha }}
    secrets: inherit 

  test:
    runs-on: self-hosted
    needs: build-image
    steps:     
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: ghcr.io/${{ github.repository }}:test${{ github.sha }}
          options: |
            --gpus all
          run: |
            python tests/test_nccl_timeout.py

