name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

env:
  IMAGETAG: test$(git rev-parse --short HEAD)

jobs:
  build-image:
    uses: ./.github/workflows/build_image.yml
    with:
      runs-on: self-hosted
      tag: ${{ env.IMAGETAG }}
    secrets: inherit 

  test:
    runs-on: self-hosted
    needs: build-image
    steps:     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: nvidia-cosmos/${{ github.repository }}/${{ env.IMAGETAG }}
          options: |
            --gpus all
          run: |
            python tests/test_nccl_timeout.py

