name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  # 计算变量
  preset-variables:
    outputs:
      image_tag: test$(git rev-parse --short HEAD)

  build-image:
    needs: preset-variables
    uses: ./.github/workflows/build_image.yml
    with:
      runs-on: self-hosted
      tag: ${{ needs.preset-variables.outputs.image_tag }}
    secrets: inherit 

  test:
    runs-on: self-hosted
    needs: [preset-variables, build-image]
    steps:     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: nvidia-cosmos/${{ github.repository }}:${{ needs.preset-variables.outputs.image_tag }}
          options: |
            --gpus all
        run: |
          python tests/test_nccl_timeout.py

