name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build image
        run: |
          docker build -t ${{ github.repository }}:test${{ github.sha }} .

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          # registry: ghcr.io
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ github.repository }}:test${{ github.sha }}
          options: |
            --gpus all
          shell: /bin/bash
          run: |
            # prepare code
            git clone https://github.com/${{ github.repository }}.git
            cd cosmos-rl
            git checkout ${{ github.sha }}

            # run tests
            python tests/test_cache.py
            # torchrun --nproc_per_node=4 tests/test_comm.py
            python tests/test_fp8.py
            # python tests/test_grad_allreduce.py
            # python tests/test_high_availability_nccl.py
            python tests/test_nccl_collectives.py
            # python tests/test_nccl_timeout.py
            # python tests/test_parallel_map.py
            # python tests/test_policy_to_policy.py
            # python tests/test_policy_to_rollout.py
            # python tests/test_process_flow.py

